// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qwziqpnzelwpfxjapnaz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF3emlxcG56ZWx3cGZ4amFwbmF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk5Mzg5NTEsImV4cCI6MjA1NTUxNDk1MX0.IkJ2in_E25RUndU3_h_0NL_Zp_RBV0e6BcvdD3Y4mpI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);